hy-sql/hy-sql-backend

.circleci/config.yml
.gitignore
package.json

Testikattavuusraportti, pyörii Circlessä

test coverage report script added, runs in CI

---

.circleci/config.yml
README.md

Testikattavuusraportit menee CI:n kautta codecovhun

Testcoverage

---

.prettierrc
models/state.js
package-lock.json
tests/state.test.js

Luotu pohjat state-objektille tietokantaoperaatioiden tilanhallintaan. Metodeille välitetään parametrina parsittu command-objekti. INSERT INTO -metodi täydentyy kunhan komentovalidointi ja komento-objektin parsiminen saadaan toteutettua. Yksikkötestejä kirjoitettu varmistamaan luokan toimintaa.

Stateobjectclass

---

commands/createTableCommand.js
commands/parser.js
models/CreateTableSchema.js
tests/createTableCommand.test.js

Create table test

---

.eslintrc.js
commands/insertIntoCommand.js
commands/parser.js
models/InsertIntoSchema.js
package.json

InsertInto command, validation, indent error set to 'warn' in eslint, ready written Insert tester in parser. No execution middleware yet. Returns { name: 'INSERT INTO', error: 'VALUES missing' } if VALUES missing.

ready to merge?

---

models/SelectAllSchema.js

Lisätty Select *:lle muiden komentojen kanssa yhtenevä nimen maksimipituuden tarkistus.

Added maximum length validation for table name in SelectAllSchema

---

commands/insertIntoCommand.js
models/InsertIntoSchema.js
tests/insertIntoCommand.test.js

Pitäis toimia odotetusti suurimmassa osassa tapauksista yhdellä taululla. Palauttaa vielä sen ruman errorin.

Insert validate,command,tests

---

requests/postQuery.rest
requests/postQuery_heroku.rest

Korjasin yhden VSCode REST Client testitapauksen: Kuten tapauksen ylle on kommentoitu tapauksen oli tarkoituksena sisältää virheellinen CREATE TABLE kysely siihen vahingossa jääneen validin kyselyn sijaan.  Nyt kommentit ja niiden alla olevat tapaukset vastaavat toisiaan.

Corrected an error in VSCode REST Client test case

---

commands/insertIntoCommand.js

Kirjoitan koko homman uudelleen että kaikki nuo erilaiset validit muodot toimivat oikein, mutta tämä palauttaa errorin joka toimii oikein nykyisessä kehikossa jos keyword puuttuu. Lisäksi korjattu forEach => map nuolifunktioiksi.

kirjoitettu insert joka toimii NYT

---

.eslintrc.js
commands/insertIntoCommand.js
requests/postQuery.rest
requests/selectTester.rest
services/StateService.js
tests/stateService.test.js

Backlogilta 17 + 35-38
- SELECT sarake_1, sarake_2 FROM ... kyselyt palauttaa halutut sarakkeet ja virheen jos taulua ei olemassa
- INSERT INTO ilmoittaa jos väärää datatyyppiä yritetään tallentaa sarakkeeseen.
- Testejä lisätty

State select

---

commands/selectCommand.js
models/SelectSchema.js
tests/selectCommand.test.js

some simple test cases, and bugfix to SelectSchema missing {} on imports/exports

Select tests

---

_requests/selectTester.rest
requests/postQuery.rest
requests/postQuery_heroku.rest
services/StateService.js
tests/stateService.test.js

SELECT * FROM ... WHERE -integroitu stateServiceen

Stateservice where

---

_requests/create_table.rest
commands/orderByCommand.js
commands/selectAllCommand.js
commands/selectCommand.js
models/OrderBySchema.js
models/SelectSchema.js
services/StateService.js
tests/selectAllOrderByCommand.test.js
tests/selectColumnsOrderBy.test.js
tests/stateService.test.js

Waiting for stateservice-where branch

Select columns order by

---

requests/postQuery.rest
services/StateService.js
tests/stateService.test.js

stateService päivitetty SELECT column_1, column_2 FROM ... WHERE ... kyselyille.

Select columns where

---

_requests/create_table.rest
tests/stateService.test.js

create StateService tests for selectAllWhereOrderBy

---

commands/whereCommand.js
models/CreateTableSchema.js
models/InsertIntoSchema.js
models/OrderBySchema.js
models/SelectSchema.js
models/WhereSchema.js
tests/selectAllCommand.test.js

Lisätty puuttuvia custom virheviestejä Schemoihin ja pieni korjaus WhereCommandiin ja tälle korjaukselle lisätty testi

More custom messages

---

.eslintrc.js
commands/whereCommand.js
models/WhereSchema.js
tests/selectAllWhereOrderByCommand.test.js
tests/selectColumnsWhereOrderBy.test.js
tests/whereCommand.test.js

Where validointi tarkastaa nyt päättyykö ja alkaako merkkijono merkillä '  ja ettei WHERE osio sisällä odotettua enempää '-merkkejä

Added quote checks to WHERE parsing and validation schema

---

.eslintrc.js
_requests/create_table.rest
commands/createTableCommand.js
commands/insertIntoCommand.js
commands/orderByCommand.js
commands/selectAdvancedCommand.js
commands/selectAllCommand.js
models/CreateTableSchema.js
models/SelectAdvancedSchema.js
package-lock.json
package.json
services/StateService.js
services/commandService.js
tests/insertIntoCommand.test.js
tests/routes.test.js
tests/selectAdvancedCommand.test.js
tests/stateServiceSelectAdvanced.test.js
tests/stateServiceSelectAll.test.js
tests/stateServiceSelectColumns.test.js
utils/calculateExpression.js
utils/containsOperator.js
utils/executeFunction.js
utils/parseColumnFromFunction.js
utils/parseColumnsFromExpression.js
utils/regex.js

Lisäsin eslint-plugin-prettier sekä eslint-config-prettier, kun eslint valitti kokoajan sisennysvirheistä. Keskitin kaikki meidän käytettävät säännölliset lausekkeet utils/regex.js tiedostoon, kuten myös jotkut apufunktiot.

Select with operations

---

commands/deleteCommand.js
commands/parserTools/checkForAdditional.js
commands/selectAllCommand.js
models/DeleteSchema.js
services/commandService.js
tests/deleteCommand.test.js
tests/selectAllCommand.test.js

Delete command ja sen validointi. Lisäksi vähän refaktorointia. DELETE ja DELETE WHERE + molemmille testit. StateServiceen integrointi erillisessä commitissa myöhemmin.

Delete command and schema

---

commands/updateCommand.js
models/UpdateSchema.js
tests/updateColumnsWhereCommand.test.js

Validointi lisätty update-komennoille joissa WHERE-ehto.

UPDATE command WHERE

---

models/State.js
models/UpdateSchema.js
requests/postQuery.rest
services/StateService.js
tests/stateServiceUpdate.test.js
tests/stateServiceUpdateColumnsWhere.test.js

UPDATE ja UPDATE WHERE integroitu stateServiceen. Testit lisätty

State service update

---

.gitignore
models/State.js
requests/postQuery.rest
services/StateService.js
tests/stateServiceDelete.test.js

Delete kyselyjen käsittely stateServicessa ja sille testit

StateService delete

---

tests/selectAdvancedWhere.test.js

Testicaseja select ... where ... validointiin aritmeettisten lausekkeiden ja funktiokutsujen kanssa. Virheellisiin kyselyihin liittyvät testit ei vielä mene läpi ja on siksi kommentoitu.

Select advanced unit tests

---

Dockerfile

Created Dockerfile to push images to dockerhub.

create Dockerfile to build docker images

---

services/StateService.js
tests/integration/stateServiceSelectAdvanced.test.js

Fixed only one aggregate function getting handled in queries

---

commandParsers/deleteParser.js
commandParsers/fieldParser.js
commandParsers/limitParser.js
commandParsers/parserTools/addErrorToValidationResult.js
commandParsers/parserTools/checkCorrectPosition.js
commandParsers/parserTools/queryContains.js
commandParsers/selectParser.js
schemas/ExpressionSchema.js
schemas/GroupBySchema.js
schemas/LimitSchema.js
schemas/OrderBySchema.js
schemas/SelectSchema.js
schemas/WhereSchema.js
services/StateService.js
tests/integration/stateServiceSelectWithLimit.test.js
tests/unit/limitParser.test.js
tests/unit/whereParser.test.js

LIMIT OFFSET toteutus ja testit. 
Huomautuksena LIMIT ja OFFSET toteutuksista: 
- arvoina voidaan antaa numeroita ja laskuoperaatioita, joissa numeroita ja laskuoperaattoreita. 
- Arvo voi siis olla negatiivinen. Negatiivisten arvojen käsittelyyn vaikutti olevan monia eri toteutuksia olemassa. Päädyin ratkaisemaan stateServicessa negatiivisten arvojen käsittelyn palauttamalla errorin muotoa { error: 'Value given to LIMIT or OFFSET is negative.'.}. 
- palauttaa errorin jos palautettavia rivejä ei jää jäljelle. Error muotoa: 
{ error: 'No rows left to return. Try changing value given to LIMIT or OFFSET.' }

Limit offset

---

commandParsers/deleteParser.js
commandParsers/limitParser.js
commandParsers/parserTools/checkForAdditional.js
commandParsers/selectParser.js
tests/integration/stateServiceSelectWithLimit.test.js
tests/unit/limitParser.test.js
tests/unit/selectAdvanced.test.js

Fixed using offset without limit not causing an error (linked issue #110 ). Also added a test for it. Fixed some typos and did a tiny refactor in one file. Fixed a problem with an error thrown from deleteParser.

Offset fix

---

_requests/postQuery.rest
_requests/postQuery_heroku.rest
tests/integration/summaryQueries.test.js

Automated some user story test cases

Integration tests

---

_requests/create_table.rest
commandParsers/parserTools/splitExpressionIntoArray.js
services/StateService.js
services/components/functions.js
tests/integration/stateService.test.js
tests/integration/stateServiceSelectWithAritmeticAndFunctions.test.js
tests/unit/functions.test.js
tests/unit/groupByParser.test.js
tests/unit/selectParser/selectColumnsOrderBy.test.js
tests/unit/selectParser/selectParser.test.js

State service refactoring
